### ISSUE TITLE
A few more references I found very useful for me

### ISSUE THREAD

**Issue by JeanBilheux** [knoxpy/python-resources#1]
//new README.md

# Resources for Python

[:books: Books](#books) | [:office: Conferences](#conferences) | [:bird: Twitter](#twitter)

Feel free to submit your own links and categories via [Pull Requests](https://github.com/knoxpy/python-resources/pulls) or [Issues](https://github.com/knoxpy/python-resources/issues).

### General
[The Hacker's Guide to Python](http://www.amazon.com/gp/product/1304819248/) by Julien Danjou  
[Effective Python: 59 Specific Ways to Write Better Python](http://www.amazon.com/dp/0134034287/) by Brett Slatkin  
[Guide to NumPy: 2nd Edition](http://www.amazon.com/dp/151730007X/) by Travis E. Oliphant  

### Testing
[Testing Python](http://www.amazon.com/Testing-Python-Applying-Unit-Acceptance/dp/1118901223/ref=sr_1_1?ie=UTF8&qid=1456152563&sr=8-1&keywords=testing+python) by David Sale

### libraries
[Matplotlib for Python Developers](http://www.amazon.com/Matplotlib-Python-Developers-Tosi-Sandro/dp/1847197906/ref=sr_1_1?ie=UTF8&qid=1456152616&sr=8-1&keywords=matplotlib+for+python+developers) by Sandro Tosi

### iPython
[IPython Interactive Computing and Visualization Cookbook)[http://www.amazon.com/IPython-Interactive-Computing-Visualization-Cookbook/dp/1783284811/ref=sr_1_1?ie=UTF8&qid=1456152666&sr=8-1&keywords=ipython+interactive+computing+and+visualization+cookbook) by Cyrille Rossant

## Conferences
[PyTennessee](https://www.pytennessee.org) in Nashville, TN  
[SciPy Conferences](http://conference.scipy.org) in various locations  
[PyCon](https://us.pycon.org/) in various locations  
[PyData](http://pydata.org) in various locations

## Twitter
[Travis Oliphant](https://twitter.com/teoliphant) creator of SciPy, author of NumPy, CEO and co-founder of Continuum Analytics  
[Continuum Analytics](https://twitter.com/ContinuumIO) creator and driving force behind Anaconda

**Comment by wigging** [comment]
Added your references to the resources list. Thank you for the suggestions.
